Repository lblod/frontend-burgernabije-besluitendatabank, pull requests merged in 2023-11, with the labels that each got.

#153 Setup `release-it`
  .release-it.json
  package-lock.json
  package.json
Labels: enhancement

#154 fix: :bug: fixed footer on stats page
  app/templates/data-quality.hbs
Labels: bug

#148 Daterange update
  app/components/filters/date-range-filter.hbs
  app/components/filters/date-range-filter.ts
  app/components/filters/date-range-filter/date-input.hbs
  app/components/filters/date-range-filter/toggle-button.hbs
  app/templates/application.hbs
  package-lock.json
  package.json
  tests/integration/components/filters/date-range-filter-test.js
Labels: enhancement

#155 refactor: :speech_balloon: updated text
  app/components/faq-card.hbs
  app/components/layout-detail.hbs
  app/templates/help.hbs
Labels: enhancement

#157 Add release workflow
  README.md
Labels: documentation

#158 Fix/footer-overhaul
  app/components/agenda-item-card.hbs
  app/components/layout-detail.hbs
  app/components/layout-home.hbs
  app/components/layout-list.hbs
  app/components/session.hbs
  app/templates/accessibility-statement.hbs
  app/templates/agenda-items/agenda-item/index.hbs
  app/templates/agenda-items/index.hbs
  app/templates/application.hbs
  app/templates/cookie-notice.hbs
  app/templates/data-quality.hbs
  app/templates/disclaimer.hbs
  app/templates/error.hbs
  app/templates/four-oh-four.hbs
  app/templates/help.hbs
  app/templates/home.hbs
  app/templates/municipality.hbs
  app/templates/sessions/index.hbs
Labels: bug

#160 Revert "Merge pull request #138 from lblod/feat/feedback-button"
  app/components/feedback-widget.hbs
  app/styles/app.scss
  app/styles/components/_c-feedback-widget.scss
  app/templates/application.hbs
Labels: enhancement

#159 Remove search description in help page
  app/templates/help.hbs
Labels: enhancement

#162 Text/data-quality-text-update
  app/models/agenda-item.ts
  app/templates/agenda-items/agenda-item/index.hbs
  app/templates/data-quality.hbs
Labels: enhancement

#161 Clean municipality list
  app/controllers/agenda-items/index.ts
  app/controllers/home.ts
  app/controllers/sessions/index.ts
  app/services/municipality-list.ts
  tests/unit/services/municipality-list-test.js
Labels: enhancement

#163 fix: :bug: added overflow class to safeguard small home component
  app/styles/components/_c-home.scss
  app/templates/home.hbs
Labels: bug

#164 Add search feature description
  app/templates/help.hbs
Labels: enhancement

#165 Fix helpage page contact email
  app/templates/help.hbs
Labels: bug

#167 Improve help and data-quality text
  app/templates/data-quality.hbs
  app/templates/help.hbs
Labels: enhancement

#169 Typo in search placeholder
  app/templates/agenda-items/index.hbs
  app/templates/home.hbs
Labels: bug

#170 Fix data-quality button position on mobile
  app/styles/app.scss
  app/templates/agenda-items/agenda-item/index.hbs
Labels: bug

#151 Statistics page
  README.md
  app/components/graph-bar-row.hbs
  app/controllers/agenda-items/agenda-item.ts
  app/controllers/data-quality.ts
  app/helpers/divide.ts
  app/models/agenda-item.ts
  app/models/governing-body-classification-code.ts
  app/models/governing-body.ts
  app/routes/data-quality.ts
  app/routes/sessions/index.ts
  app/styles/_shame.scss
  app/templates/agenda-items/agenda-item.hbs
  app/templates/data-quality.hbs
  config/environment.js
Labels: enhancement
