Repository lblod/frontend-burgernabije-besluitendatabank, pull requests merged in 2024-01, with the labels that each got.

#182 feat: ✨ service-widget
  app/index.html
  app/styles/_shame.scss
Labels: enhancement

#180 bug: 🐛 data quality modal title fix
  app/controllers/agenda-items/session.ts
  app/controllers/sessions/session.ts
  app/models/agenda-item.ts
  app/routes/agenda-items/agenda-item.ts
  app/templates/agenda-items/agenda-item.hbs
Labels: bug

#176 feat: :sparkles: province-filter
  app/components/filters/filter.ts
  app/components/filters/select-filter.ts
  app/components/filters/select-multiple-filter.ts
  app/config/constants.ts
  app/controllers/agenda-items/index.ts
  app/controllers/home.ts
  app/routes/agenda-items/index.ts
  app/services/government-list.ts
  app/services/municipality-list.ts
  app/services/province-list.ts
  app/styles/_shame.scss
  app/templates/agenda-items/index.hbs
  app/templates/home.hbs
  tests/unit/services/municipality-list-test.js
Labels: enhancement

#184 Fix/agenda-items-no-name-list
  app/templates/agenda-items/agenda-item.hbs
  package-lock.json
  package.json
Labels: enhancement

#185 Use resolution title as fallback in titleFormatted
  app/models/agenda-item.ts
Labels: enhancement

#187 feat: :sparkles: search in home power select
  app/templates/home.hbs
Labels: enhancement

#186 fix: :bug: open accordion when a bestuursorgaan is being queried
  app/components/accordion.hbs
  app/components/accordion.ts
  app/controllers/agenda-items/index.ts
  app/templates/agenda-items/index.hbs
  tests/integration/components/accordion-test.js
Labels: enhancement

#189 Refactor: Remove dead code
  app/components/navigation-bar.hbs
  app/components/navigation-bar.ts
  app/components/navigation-bar/link.hbs
  app/components/navigation-bar/link.ts
  app/components/participant-card.hbs
  app/controllers/application.ts
  app/router.ts
  app/routes/help.ts
  app/routes/municipality.ts
  app/templates/municipality.hbs
Labels: internal

#190 Update accessibility statement URL
  app/templates/accessibility-statement.hbs
Labels: bug
